# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

$RNMapboxMapsImpl = 'mapbox'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.yoomoney.ru/scm/sdk/cocoa-pod-specs.git'

platform :ios, 18.0
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OnviMobile' do
  config = use_native_modules!

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  
  # Firebase настройка
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase/Core'
  pod 'Firebase/Messaging' 
  pod 'lottie-ios', :modular_headers => false

  pod 'YooKassaPaymentsApi', '2.25.0'
  pod 'YooKassaPayments',
      :git => 'https://git.yoomoney.ru/scm/sdk/yookassa-payments-swift.git',
      :tag => '7.4.0'
  
  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'YooKassaPayments' || target.name == 'YooKassaPaymentsApi'
          config.build_settings['SWIFT_EMIT_MODULE_INTERFACE'] = 'NO'
          config.build_settings['DEFINES_MODULE'] = 'NO'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        else
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end