# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.yoomoney.ru/scm/sdk/cocoa-pod-specs.git'

platform :ios, 18.0
prepare_react_native_project!

$RNFirebaseAsStaticFramework = true
$RNMapboxMapsImpl = 'mapbox'

project 'OnviMobile',
  'Staging Debug' => :debug,
  'Staging Release' => :release

target 'OnviMobile' do
  config = use_native_modules!
  
  use_frameworks! :linkage => :static
  
  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'lottie-ios', :modular_headers => false

  pod 'YooKassaPayments',
      :git => 'https://git.yoomoney.ru/scm/sdk/yookassa-payments-swift.git',
      :tag => '8.1.0'
  
  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end